export const AUTH_USER = 'AUTH';
export const AUTH_ERROR_SIGNUP = 'AUTH_ERROR_SIGNUP';
export const AUTH_ERROR_SIGNIN = 'AUTH_ERROR_SIGNIN';
export const AUTH_EXPIRY_TOKEN = 'AUTH_EXPIRY_TOKEN';
export const REFRESH_TOKEN_ERROR = 'REFRESH_TOKEN_ERROR';
export const REFRESH_TOKEN_RESTART_TIMEOUT = 'REFRESH_TOKEN_RESTART_TIMEOUT';
